name: smartexpense

services:

  postgres:

    image: postgres:17

    container_name: smartexpense-db

    restart: unless-stopped

    environment:
      POSTGRES_DB: smartexpense
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - smartexpense-network

  app:

    build: .

    container_name: smartexpense-api

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/smartexpense
      DB_USER: postgres
      DB_PASS: postgres
      JWT_SECRET: ${JWT_SECRET}

    networks:
      - smartexpense-network

volumes:

  postgres_data:
    name: smartexpense_postgres_data

networks:

  smartexpense-network:
    driver: bridge