services:

  postgres:
    image: postgres:17-alpine
    container_name: smartexpense-db

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    container_name: smartexpense-backend

    build:
      context: ./SmartExpense

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGINS: ${CORS_ORIGINS}

    depends_on:
      - postgres


  frontend:
    container_name: smartexpense-frontend

    build:
      context: ./smart-expense-frontend
      args:
        VITE_API_URL: ${VITE_API_URL}

    ports:
      - "8081:80"

    depends_on:
      - backend



volumes:
  postgres_data: